name: task06-regression-ci
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Compile Java
        shell: bash
        run: |
          find . -name "*.java" > sources.txt
          javac -d out @sources.txt
      - name: Golden Test
        shell: bash
        run: java -cp out com.example.tests.golden.GoldenTestRunner

